= Andrew Sim - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: UltiStudent

---

== Overview


UltiStudent is a student application that effectively tackles the problem of having too many applications to manage
their school life. To improve the quality of student life in computing, UltiStudent provides a centralised platform
for them to manage their homework, cumulative average point and notes.

My role was to design and write the codes for the features in CAP manager. THe following sections of this document
illustrate the enhancement i made and also

Do note the following callouts and formatting used in this document.

=== Callouts and Format


=== Definitions of Terms
Across our project and documents, the term `cap entry` is used a lot, especially so for the CAP Manager.
In our Developer Guide and Code, we use this term `cap entry` to refer to what the CAP Manager stores and keeps track
of. This was done intentionally to avoid confusion for developers as the NotesManager and HomeworkManager of UltiStudent
both store and organise documents by the module the document is for.
However, we are aware that to the users, it is more intuitive to consider that the CAP manager stores modules and keep
tracks of the grades of the said modules, hence in our User Guide, we describe module as what the CAP manager stores.

== Summary of contributions
* *Code contributed*: https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=andrewscw&sort=displayName&since=2019-02-10&until=2019-04-14&timeframe=day&reverse=false&repoSort=true[RepoSense]

* *Major enhancement*: Developed the logic, model and storage components of the CAP manager feature of UltiStudent.
Which allow users to record the modules they have taken and the grades they received. This lets users keep track and forecast their CAP score.

** What it does: CAP Manager allows users to add, delete and edit cap entries. The CAP Manager also automatically calculates
the user's CAP score whenever a change is made in the CAP manager. CAP Manager also allows users to filter through the
cap entries they have taken by the semester by the `find-sem` command.

** Justification: The features in CAP manager helps.
Allows users to forecast their cap score in advance, this lets users be able toquantify the importance of each grade,
such that if they wish to pull up their CAP, they would know how many 'A's they require.
s feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.

** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
*** Ensured loose coupling between each manager and seamless integration of CAP manager into UltiStudent.

** Enhancements to existing features:
*** Wrote unit and integration tests for CAP manager's commands and model.  (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
*** Wrote the introduction for the Developer Guide.

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=capmanager]
include::../UserGuide.adoc[tag=add-cap]
include::../UserGuide.adoc[tag=edit-cap]
include::../UserGuide.adoc[tag=edit-cap-mc]
include::../UserGuide.adoc[tag=delete-cap]
include::../UserGuide.adoc[tag=find-cap]
include::../UserGuide.adoc[tag=list-cap]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=edit-cap]

include::../DeveloperGuide.adoc[tag=delete-cap]


== PROJECT: UltiStudent

---
