= Lim Zheng Jie Benjamin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:toc:
:toc-title: Table of Contents
:sectnums:

== Overview

This portfolio documents my contributions towards the UltiStudent project
which is part of an introductory software engineering module known as **CS2103T - Software Engineering**.
During this module, we have been provided with a working software application
that could enhance and morph our application to suit our target audience.

The purpose of this document is to present the principles and practical skills
I have learnt throughout the course of this module.

== PROJECT: UltiStudent

*UltiStudent* is a student application that effectively tackles the problem of having too many applications to manage
their school life. Having a large number of different platforms can lead to inconvenience, incompatibilities
and inorganisation. *UltiStudent* tackles this problem by providing a centralised platform
for them to manage their homework, Cumulative Average Point (CAP) and notes to improve the quality of their school life.

*UltiStudent* provides a Command Line Interface (CLI) for students to interact with and is complemented by a
Graphical User Interface (GUI). We have designed the application with the user in mind.

== Summary of contributions

|===
|This section contains the key contributions I have made towards this project. They highlight my ability to +
1) model and design the application to cater to our target users. +
2) create a working software application that is user-friendly and error-free. +
3) design and create test cases to ensure that the Homework Manager is bug free.
|===

* *Major Enhancement*:
** Developed the `Model`, `Logic` and `Storage` infrastructure for the Homework Manager.
*** *Functionality*: Allows the user to `add`, `delete`, `edit`, `find` and `list` in the homework entries. Provides the
foundations on which these features are built.
*** *Justification:* The ability to create homework entries and other features such as edit depends on the Homework Manager
                   infrastructure. This enhances the features of the UltiStudent by allowing students
                   to manage their homework on our application.
*** *Highlights:* This enhancement is a core component of our application. It affects the current functionalities of our
application and the future extensions of our application. To do this well, it requires an in-depth understanding of the
initial infrastructure of the software in order to alter it. The implementation was also difficult because of the various abstraction
layers that had to be understood.

* *Minor enhancement*:
** *Edit Homework command* that edits the attributes of current existing homework entries based on user input.
** *Delete Homework command* that deletes the attributes whose note name has the keywords
indicated by the user.
** *Find Module command* that filters all the homework entries based on a list of modules.
** *List Homework command* that shows the entire list of homework entries in the Homework Manager.

* *Code contributed*: Click
https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=LimZhengJieBenjamin[here]
to view my code on the CS2103T Project Code Dashboard.

* *Other contributions*:

** Project management:
*** Helped to manage issue tracker for our project repository.
*** Planned the project milestones for the Homework Manager feature of UltiStudent.
** Enhancements to existing features:
*** Wrote test cases for Homework Manager. (Pull requests https://github.com/cs2103-ay1819s2-w09-1/main/pull/91[#91],
https://github.com/cs2103-ay1819s2-w09-1/main/pull/87[#87])
*** Constructed sample data for the product demo of our application. (Pull request https://github.com/cs2103-ay1819s2-w09-1/main/pull/184[#184])
** Documentation:
*** User Guide
**** Revamped the tone of the User Guide to make it sound more friendly.
*** Developer Guide
**** Created UML diagrams to better explain the `edit-hw` and `find-mod` commands in the Developer Guide.
**** Discussed the pros and cons of different implementations considered during the design stage.
** Community:
*** Contributed to forum discussions.  https://github.com/nus-cs2103-AY1819S2/forum/issues/25[#25]
** Tools:
*** Assisted teammate in the integration of the Travis CI into our repository.

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

|===
|The following are the contributions I have made to the User Guide. They demonstrate my ability to write
clear and concise documentation
in friendly and inviting manner targeted at non-technical users.
|===

include::../UserGuide.adoc[tag=edit-hw]
include::../UserGuide.adoc[tag=delete-hw]
include::../UserGuide.adoc[tag=find-mod]
include::../UserGuide.adoc[tag=list-hw]

== Contributions to the Developer Guide

|===
|The following are the contributions I have made to the Developer Guide.
They demonstrate my ability to present and explain
complicated technical information in a comprehensible manner. It also showcases my technical skills and abilities.
|===

include::../DeveloperGuide.adoc[tag=deletehomework]
include::../DeveloperGuide.adoc[tag=edithomework]
include::../DeveloperGuide.adoc[tag=findmodule]

---

