= Lim Zheng Jie Benjamin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:toc:
:toc-title: Table of Contents
:sectnums:

==

== Overview

This portfolio documents my contributions towards the UltiStudent project which is part of an introductory software engineering module
known as **CS2103T - Software Engineering**. During this module, we have been provided with a working software application
and could enhance and morph our application to suit our target audience.

The purpose of this document is present the principles and practical skills
I have learnt throughout the course of this module.

== PROJECT: UltiStudent

*UltiStudent* is a student application that effectively tackles the problem of having too many applications to manage
their school life. Having a large number of different platforms can lead to inconvenience, incompatibilities
and inorganisation. *UltiStudent* tackles this problem by providing a centralised platform
for them to manage their homework, cumulative average point and notes to improve the quality of their school life.

*UltiStudent* provides a Command Line Interface (CLI) for students to interact with and is complemented by a
Graphical User Interface (GUI). We have designed the application with user-friendliness in mind.

---

== Summary of contributions

|===
|This section contains the key contributions I have made towards this project. They highlight my ability to +
1) model and design the application to cater to our target users.
2) create a working software application that is user-friendly and error-free.
3) design and create  test cases which
|===

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

|===
|The following are the contributions I have made to the User Guide. They demonstrate my ability to write clear and concise documentation
in friendly and inviting manner targeted at non-technical users.
|===

include::../UserGuide.adoc[tag=edit-hw]
include::../UserGuide.adoc[tag=delete-hw]
include::../UserGuide.adoc[tag=find-mod]
include::../UserGuide.adoc[tag=list-hw]

== Contributions to the Developer Guide

|===
|The following are the contributions I have made to the Developer Guide. They demonstrate my ability to present and explain
complicated technical information in a comprehensible manner. It also showcases my technical skills and abilities.
|===

include::../DeveloperGuide.adoc[tag=deletehomework]
include::../DeveloperGuide.adoc[tag=edithomework]
include::../DeveloperGuide.adoc[tag=findmodule]


